SET LINESIZE 200;
SET PAGESIZE 100;
PROMPT --- ALP_ESTADO_PAGO ---
SELECT ESP_CODIGO, ESP_NOMBRE FROM ALP_ESTADO_PAGO;
PROMPT --- ALP_ESTADO_ORDEN ---
SELECT ESO_CODIGO, ESO_NOMBRE FROM ALP_ESTADO_ORDEN;
PROMPT --- ALP_TIPO_COMPROBANTE ---
SELECT TCO_CODIGO, TCO_NOMBRE FROM ALP_TIPO_COMPROBANTE;
EXIT;
