-- ============================================================================
-- PROYECTO: MUEBLES LOS ALPES - BLOQUES 6 Y 7
-- MOTOR: Oracle Database 21c
-- ============================================================================

-- ============================================================================
-- BLOQUE 6: INVENTARIOS Y BODEGAS
-- ============================================================================
-- Descripción: Gestión de inventario, movimientos, bodegas y stock
-- Incluye: Control de existencias, ajustes, tomas físicas, reservas
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tabla: ALP_BODEGA
-- Descripción: Bodegas o almacenes físicos
-- Ejemplos: 'Bodega Central', 'Almacén Zona 10', 'Bodega Producción'
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_BODEGA (
    BOD_BODEGA               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOD_CODIGO               VARCHAR2(50) NOT NULL UNIQUE,
    BOD_NOMBRE               VARCHAR2(150) NOT NULL,
    BOD_DIRECCION            VARCHAR2(500),
    BOD_ESTADO               VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    BOD_FECHA_CREACION       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT CHK_BOD_ESTADO CHECK (BOD_ESTADO IN ('ACTIVO', 'INACTIVO', 'MANTENIMIENTO'))
);

COMMENT ON TABLE ALP_BODEGA IS 'Catálogo de bodegas y almacenes físicos';

CREATE INDEX IDX_BOD_ESTADO ON ALP_BODEGA(BOD_ESTADO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_ZONA_BODEGA
-- Descripción: Zonas o ubicaciones dentro de una bodega
-- Ejemplos: 'Zona A-1', 'Pasillo 5', 'Rack 10'
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_ZONA_BODEGA (
    ZBO_ZONA_BODEGA          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOD_BODEGA               NUMBER NOT NULL,
    ZBO_CODIGO               VARCHAR2(50) NOT NULL,
    ZBO_NOMBRE               VARCHAR2(150) NOT NULL,
    ZBO_DESCRIPCION          VARCHAR2(500),
    ZBO_ESTADO               VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    ZBO_FECHA_CREACION       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_ZBO_BODEGA FOREIGN KEY (BOD_BODEGA) 
        REFERENCES ALP_BODEGA(BOD_BODEGA),
    CONSTRAINT UNQ_ZBO_BODEGA_CODIGO UNIQUE (BOD_BODEGA, ZBO_CODIGO),
    CONSTRAINT CHK_ZBO_ESTADO CHECK (ZBO_ESTADO IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'))
);

COMMENT ON TABLE ALP_ZONA_BODEGA IS 'Ubicaciones y zonas dentro de bodegas';

CREATE INDEX IDX_ZBO_BODEGA ON ALP_ZONA_BODEGA(BOD_BODEGA);
CREATE INDEX IDX_ZBO_CODIGO ON ALP_ZONA_BODEGA(ZBO_CODIGO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_TIPO_MOVIMIENTO
-- Descripción: Tipos de movimientos de inventario
-- Ejemplos: 'ENTRADA_COMPRA', 'SALIDA_VENTA', 'AJUSTE_POSITIVO', 'TRANSFERENCIA'
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_TIPO_MOVIMIENTO (
    TMO_TIPO_MOVIMIENTO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TMO_CODIGO               VARCHAR2(50) NOT NULL UNIQUE,
    TMO_NOMBRE               VARCHAR2(150) NOT NULL,
    TMO_AFECTA_STOCK         VARCHAR2(1) NOT NULL,
    TMO_DESCRIPCION          VARCHAR2(500),
    
    CONSTRAINT CHK_TMO_AFECTA CHECK (TMO_AFECTA_STOCK IN ('S', 'N'))
);

COMMENT ON TABLE ALP_TIPO_MOVIMIENTO IS 'Catálogo de tipos de movimientos de inventario';
COMMENT ON COLUMN ALP_TIPO_MOVIMIENTO.TMO_AFECTA_STOCK IS 'S = modifica existencias, N = solo registro';

-- ----------------------------------------------------------------------------
-- Tabla: ALP_INVENTARIO_TIPO_MOVIMIENTO (Redundante con ALP_TIPO_MOVIMIENTO)
-- Nota: Parece duplicada, se mantiene por si hay lógica específica diferente
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_INVENTARIO_TIPO_MOVIMIENTO (
    ITM_INVENTARIO_TIPO_MOV  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITM_CODIGO               VARCHAR2(50) NOT NULL UNIQUE,
    ITM_NOMBRE               VARCHAR2(150) NOT NULL,
    ITM_DESCRIPCION          VARCHAR2(500),
    ITM_ESTADO               VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    
    CONSTRAINT CHK_ITM_ESTADO CHECK (ITM_ESTADO IN ('ACTIVO', 'INACTIVO'))
);

COMMENT ON TABLE ALP_INVENTARIO_TIPO_MOVIMIENTO IS 'Catálogo alternativo de tipos de movimiento';

-- ----------------------------------------------------------------------------
-- Tabla: ALP_EXISTENCIA
-- Descripción: Stock actual por producto/variante en cada bodega/zona
-- CRÍTICO: Tabla de control de inventario en tiempo real
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_EXISTENCIA (
    EXI_EXISTENCIA           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRO_PRODUCTO             NUMBER,
    PVA_PRODUCTO_VARIANTE    NUMBER,
    BOD_BODEGA               NUMBER NOT NULL,
    ZBO_ZONA_BODEGA          NUMBER,
    EXI_CANTIDAD_DISPONIBLE  NUMBER(12,2) DEFAULT 0 NOT NULL,
    EXI_CANTIDAD_RESERVADA   NUMBER(12,2) DEFAULT 0 NOT NULL,
    EXI_CANTIDAD_MINIMA      NUMBER(12,2),
    EXI_CANTIDAD_MAXIMA      NUMBER(12,2),
    EXI_PUNTO_REORDEN        NUMBER(12,2),
    EXI_ULTIMA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_EXI_PRODUCTO FOREIGN KEY (PRO_PRODUCTO) 
        REFERENCES ALP_PRODUCTO(PRO_PRODUCTO),
    CONSTRAINT FK_EXI_VARIANTE FOREIGN KEY (PVA_PRODUCTO_VARIANTE) 
        REFERENCES ALP_PRODUCTO_VARIANTE(PVA_PRODUCTO_VARIANTE),
    CONSTRAINT FK_EXI_BODEGA FOREIGN KEY (BOD_BODEGA) 
        REFERENCES ALP_BODEGA(BOD_BODEGA),
    CONSTRAINT FK_EXI_ZONA FOREIGN KEY (ZBO_ZONA_BODEGA) 
        REFERENCES ALP_ZONA_BODEGA(ZBO_ZONA_BODEGA),
    CONSTRAINT CHK_EXI_PRODUCTO_O_VARIANTE CHECK (
        (PRO_PRODUCTO IS NOT NULL AND PVA_PRODUCTO_VARIANTE IS NULL) OR
        (PRO_PRODUCTO IS NULL AND PVA_PRODUCTO_VARIANTE IS NOT NULL)
    ),
    CONSTRAINT CHK_EXI_CANTIDADES CHECK (
        EXI_CANTIDAD_DISPONIBLE >= 0 AND 
        EXI_CANTIDAD_RESERVADA >= 0
    )
);

COMMENT ON TABLE ALP_EXISTENCIA IS 'Stock actual por ubicación (inventario perpetuo)';
COMMENT ON COLUMN ALP_EXISTENCIA.EXI_CANTIDAD_DISPONIBLE IS 'Stock libre para venta';
COMMENT ON COLUMN ALP_EXISTENCIA.EXI_CANTIDAD_RESERVADA IS 'Stock comprometido en órdenes';
COMMENT ON COLUMN ALP_EXISTENCIA.EXI_PUNTO_REORDEN IS 'Nivel de reorden automático';

CREATE INDEX IDX_EXI_PRODUCTO ON ALP_EXISTENCIA(PRO_PRODUCTO);
CREATE INDEX IDX_EXI_VARIANTE ON ALP_EXISTENCIA(PVA_PRODUCTO_VARIANTE);
CREATE INDEX IDX_EXI_BODEGA ON ALP_EXISTENCIA(BOD_BODEGA);
CREATE INDEX IDX_EXI_ZONA ON ALP_EXISTENCIA(ZBO_ZONA_BODEGA);
CREATE INDEX IDX_EXI_DISPONIBLE ON ALP_EXISTENCIA(EXI_CANTIDAD_DISPONIBLE);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_MOVIMIENTO_INVENTARIO
-- Descripción: Registro de movimientos de inventario (Kardex)
-- CRÍTICO: Auditoría completa de entradas/salidas
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_MOVIMIENTO_INVENTARIO (
    MIN_MOVIMIENTO_INVENTARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRO_PRODUCTO             NUMBER,
    PVA_PRODUCTO_VARIANTE    NUMBER,
    BOD_BODEGA               NUMBER NOT NULL,
    ZBO_ZONA_BODEGA          NUMBER,
    TMO_TIPO_MOVIMIENTO      NUMBER NOT NULL,
    VEN_ORDEN_VENTA          NUMBER,
    MIN_CANTIDAD             NUMBER(12,2) NOT NULL,
    MIN_COSTO_UNITARIO       NUMBER(12,2),
    MIN_FECHA_MOVIMIENTO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MIN_OBSERVACION          VARCHAR2(1000),
    MIN_REFERENCIA_EXTERNA   VARCHAR2(100),
    MIN_FECHA_CREACION       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_MIN_PRODUCTO FOREIGN KEY (PRO_PRODUCTO) 
        REFERENCES ALP_PRODUCTO(PRO_PRODUCTO),
    CONSTRAINT FK_MIN_VARIANTE FOREIGN KEY (PVA_PRODUCTO_VARIANTE) 
        REFERENCES ALP_PRODUCTO_VARIANTE(PVA_PRODUCTO_VARIANTE),
    CONSTRAINT FK_MIN_BODEGA FOREIGN KEY (BOD_BODEGA) 
        REFERENCES ALP_BODEGA(BOD_BODEGA),
    CONSTRAINT FK_MIN_ZONA FOREIGN KEY (ZBO_ZONA_BODEGA) 
        REFERENCES ALP_ZONA_BODEGA(ZBO_ZONA_BODEGA),
    CONSTRAINT FK_MIN_TIPO_MOVIMIENTO FOREIGN KEY (TMO_TIPO_MOVIMIENTO) 
        REFERENCES ALP_TIPO_MOVIMIENTO(TMO_TIPO_MOVIMIENTO),
    CONSTRAINT CHK_MIN_PRODUCTO_O_VARIANTE CHECK (
        (PRO_PRODUCTO IS NOT NULL AND PVA_PRODUCTO_VARIANTE IS NULL) OR
        (PRO_PRODUCTO IS NULL AND PVA_PRODUCTO_VARIANTE IS NOT NULL)
    ),
    CONSTRAINT CHK_MIN_CANTIDAD CHECK (MIN_CANTIDAD != 0)
);

COMMENT ON TABLE ALP_MOVIMIENTO_INVENTARIO IS 'Registro histórico de movimientos (Kardex)';
COMMENT ON COLUMN ALP_MOVIMIENTO_INVENTARIO.MIN_CANTIDAD IS 'Cantidad (+entrada, -salida)';
COMMENT ON COLUMN ALP_MOVIMIENTO_INVENTARIO.VEN_ORDEN_VENTA IS 'FK a orden de venta (si aplica)';

CREATE INDEX IDX_MIN_PRODUCTO ON ALP_MOVIMIENTO_INVENTARIO(PRO_PRODUCTO);
CREATE INDEX IDX_MIN_VARIANTE ON ALP_MOVIMIENTO_INVENTARIO(PVA_PRODUCTO_VARIANTE);
CREATE INDEX IDX_MIN_BODEGA ON ALP_MOVIMIENTO_INVENTARIO(BOD_BODEGA);
CREATE INDEX IDX_MIN_TIPO ON ALP_MOVIMIENTO_INVENTARIO(TMO_TIPO_MOVIMIENTO);
CREATE INDEX IDX_MIN_FECHA ON ALP_MOVIMIENTO_INVENTARIO(MIN_FECHA_MOVIMIENTO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_AJUSTE_STOCK
-- Descripción: Ajustes manuales de inventario
-- Uso: Correcciones por merma, daño, robo, conteo físico
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_AJUSTE_STOCK (
    AJS_AJUSTE_STOCK         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRO_PRODUCTO             NUMBER,
    PVA_PRODUCTO_VARIANTE    NUMBER,
    BOD_BODEGA               NUMBER NOT NULL,
    AJS_CANTIDAD_ANTERIOR    NUMBER(12,2) NOT NULL,
    AJS_CANTIDAD_NUEVA       NUMBER(12,2) NOT NULL,
    AJS_MOTIVO               VARCHAR2(500) NOT NULL,
    USU_USUARIO              NUMBER NOT NULL,
    AJS_FECHA_AJUSTE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_AJS_PRODUCTO FOREIGN KEY (PRO_PRODUCTO) 
        REFERENCES ALP_PRODUCTO(PRO_PRODUCTO),
    CONSTRAINT FK_AJS_VARIANTE FOREIGN KEY (PVA_PRODUCTO_VARIANTE) 
        REFERENCES ALP_PRODUCTO_VARIANTE(PVA_PRODUCTO_VARIANTE),
    CONSTRAINT FK_AJS_BODEGA FOREIGN KEY (BOD_BODEGA) 
        REFERENCES ALP_BODEGA(BOD_BODEGA),
    CONSTRAINT FK_AJS_USUARIO FOREIGN KEY (USU_USUARIO) 
        REFERENCES ALP_USUARIO(USU_USUARIO),
    CONSTRAINT CHK_AJS_PRODUCTO_O_VARIANTE CHECK (
        (PRO_PRODUCTO IS NOT NULL AND PVA_PRODUCTO_VARIANTE IS NULL) OR
        (PRO_PRODUCTO IS NULL AND PVA_PRODUCTO_VARIANTE IS NOT NULL)
    )
);

COMMENT ON TABLE ALP_AJUSTE_STOCK IS 'Ajustes manuales de inventario (auditoría obligatoria)';

CREATE INDEX IDX_AJS_PRODUCTO ON ALP_AJUSTE_STOCK(PRO_PRODUCTO);
CREATE INDEX IDX_AJS_VARIANTE ON ALP_AJUSTE_STOCK(PVA_PRODUCTO_VARIANTE);
CREATE INDEX IDX_AJS_BODEGA ON ALP_AJUSTE_STOCK(BOD_BODEGA);
CREATE INDEX IDX_AJS_FECHA ON ALP_AJUSTE_STOCK(AJS_FECHA_AJUSTE);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_TOMA_FISICA
-- Descripción: Tomas físicas de inventario (conteos cíclicos)
-- Uso: Conciliación periódica, auditorías
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_TOMA_FISICA (
    TFI_TOMA_FISICA          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOD_BODEGA               NUMBER NOT NULL,
    TFI_FECHA_CONTEO         DATE NOT NULL,
    TFI_FECHA_CIERRE         TIMESTAMP,
    USU_USUARIO              NUMBER NOT NULL,
    TFI_ESTADO               VARCHAR2(20) DEFAULT 'ABIERTO' NOT NULL,
    
    CONSTRAINT FK_TFI_BODEGA FOREIGN KEY (BOD_BODEGA) 
        REFERENCES ALP_BODEGA(BOD_BODEGA),
    CONSTRAINT FK_TFI_USUARIO FOREIGN KEY (USU_USUARIO) 
        REFERENCES ALP_USUARIO(USU_USUARIO),
    CONSTRAINT CHK_TFI_ESTADO CHECK (TFI_ESTADO IN ('ABIERTO', 'CERRADO', 'CONCILIADO', 'CANCELADO'))
);

COMMENT ON TABLE ALP_TOMA_FISICA IS 'Encabezado de tomas físicas de inventario';

CREATE INDEX IDX_TFI_BODEGA ON ALP_TOMA_FISICA(BOD_BODEGA);
CREATE INDEX IDX_TFI_FECHA ON ALP_TOMA_FISICA(TFI_FECHA_CONTEO);
CREATE INDEX IDX_TFI_ESTADO ON ALP_TOMA_FISICA(TFI_ESTADO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_RESERVA_STOCK
-- Descripción: Reservas temporales de inventario
-- Uso: Carritos de compra, órdenes pendientes de pago
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_RESERVA_STOCK (
    RES_RESERVA_STOCK        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRO_PRODUCTO             NUMBER,
    PVA_PRODUCTO_VARIANTE    NUMBER,
    BOD_BODEGA               NUMBER NOT NULL,
    CLI_CLIENTE              NUMBER,
    RES_CANTIDAD             NUMBER(12,2) NOT NULL,
    RES_FECHA_INICIO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RES_FECHA_EXPIRACION     TIMESTAMP NOT NULL,
    RES_MOTIVO               VARCHAR2(100),
    RES_REFERENCIA_EXTERNA   VARCHAR2(100),
    RES_ESTADO               VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    
    CONSTRAINT FK_RES_PRODUCTO FOREIGN KEY (PRO_PRODUCTO) 
        REFERENCES ALP_PRODUCTO(PRO_PRODUCTO),
    CONSTRAINT FK_RES_VARIANTE FOREIGN KEY (PVA_PRODUCTO_VARIANTE) 
        REFERENCES ALP_PRODUCTO_VARIANTE(PVA_PRODUCTO_VARIANTE),
    CONSTRAINT FK_RES_BODEGA FOREIGN KEY (BOD_BODEGA) 
        REFERENCES ALP_BODEGA(BOD_BODEGA),
    CONSTRAINT FK_RES_CLIENTE FOREIGN KEY (CLI_CLIENTE) 
        REFERENCES ALP_CLIENTE(CLI_CLIENTE),
    CONSTRAINT CHK_RES_PRODUCTO_O_VARIANTE CHECK (
        (PRO_PRODUCTO IS NOT NULL AND PVA_PRODUCTO_VARIANTE IS NULL) OR
        (PRO_PRODUCTO IS NULL AND PVA_PRODUCTO_VARIANTE IS NOT NULL)
    ),
    CONSTRAINT CHK_RES_CANTIDAD CHECK (RES_CANTIDAD > 0),
    CONSTRAINT CHK_RES_ESTADO CHECK (RES_ESTADO IN ('ACTIVO', 'LIBERADO', 'CONFIRMADO', 'EXPIRADO'))
);

COMMENT ON TABLE ALP_RESERVA_STOCK IS 'Reservas temporales de inventario (TTL)';
COMMENT ON COLUMN ALP_RESERVA_STOCK.RES_FECHA_EXPIRACION IS 'Fecha de liberación automática';

CREATE INDEX IDX_RES_PRODUCTO ON ALP_RESERVA_STOCK(PRO_PRODUCTO);
CREATE INDEX IDX_RES_VARIANTE ON ALP_RESERVA_STOCK(PVA_PRODUCTO_VARIANTE);
CREATE INDEX IDX_RES_BODEGA ON ALP_RESERVA_STOCK(BOD_BODEGA);
CREATE INDEX IDX_RES_CLIENTE ON ALP_RESERVA_STOCK(CLI_CLIENTE);
CREATE INDEX IDX_RES_ESTADO ON ALP_RESERVA_STOCK(RES_ESTADO);
CREATE INDEX IDX_RES_EXPIRACION ON ALP_RESERVA_STOCK(RES_FECHA_EXPIRACION);

-- ============================================================================
-- BLOQUE 7: PRODUCCIÓN
-- ============================================================================
-- Descripción: Gestión de producción de muebles
-- Incluye: Procesos, recetas, órdenes de producción, costos
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tabla: ALP_PROCESO
-- Descripción: Procesos de fabricación
-- Ejemplos: 'CORTE', 'ENSAMBLADO', 'LIJADO', 'BARNIZADO', 'TAPIZADO'
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_PROCESO (
    PCO_PROCESO              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PCO_CODIGO               VARCHAR2(50) NOT NULL UNIQUE,
    PCO_NOMBRE               VARCHAR2(150) NOT NULL,
    PCO_DESCRIPCION          VARCHAR2(500),
    
    CONSTRAINT CHK_PCO_CODIGO CHECK (LENGTH(PCO_CODIGO) >= 3)
);

COMMENT ON TABLE ALP_PROCESO IS 'Catálogo de procesos de manufactura';

-- ----------------------------------------------------------------------------
-- Tabla: ALP_ESTACION_TRABAJO
-- Descripción: Estaciones o centros de trabajo
-- Ejemplos: 'Área de Corte 1', 'Mesa de Ensamblado 3', 'Cabina de Pintura'
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_ESTACION_TRABAJO (
    EST_ESTACION_TRABAJO     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EST_CODIGO               VARCHAR2(50) NOT NULL UNIQUE,
    EST_NOMBRE               VARCHAR2(150) NOT NULL,
    EST_DESCRIPCION          VARCHAR2(500),
    EST_ESTADO               VARCHAR2(20) DEFAULT 'DISPONIBLE' NOT NULL,
    
    CONSTRAINT CHK_EST_ESTADO CHECK (EST_ESTADO IN ('DISPONIBLE', 'OCUPADO', 'MANTENIMIENTO', 'INACTIVO'))
);

COMMENT ON TABLE ALP_ESTACION_TRABAJO IS 'Estaciones de trabajo en planta';

CREATE INDEX IDX_EST_ESTADO ON ALP_ESTACION_TRABAJO(EST_ESTADO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_RECETA_PRODUCCION
-- Descripción: Recetas maestras de producción (BOM - Bill of Materials)
-- Define qué materiales y en qué cantidades se necesitan
-- ----------------------------------------------------------------------------

CREATE TABLE ALP_RECETA_PRODUCCION (
    RPR_RECETA_PRODUCCION    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRO_PRODUCTO              NUMBER NOT NULL,
    RPR_VERSION               VARCHAR2(20) DEFAULT '1.0' NOT NULL,
    RPR_DESCRIPCION           VARCHAR2(500),
    RPR_ACTIVO                VARCHAR2(1) DEFAULT 'S' NOT NULL,
    RPR_FECHA_CREACION        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_RECETA_PRO_PROD FOREIGN KEY (PRO_PRODUCTO) 
        REFERENCES ALP_PRODUCTO(PRO_PRODUCTO),
    CONSTRAINT UNQ_RECETA_PROD_VER UNIQUE (PRO_PRODUCTO, RPR_VERSION),
    CONSTRAINT CHK_RECETA_ACTIVO CHECK (RPR_ACTIVO IN ('S', 'N'))
);

COMMENT ON TABLE ALP_RECETA_PRODUCCION IS 'BOM - Lista de materiales para producción';

CREATE INDEX IDX_RPR_PROD_BUSQUEDA ON ALP_RECETA_PRODUCCION(PRO_PRODUCTO);
CREATE INDEX IDX_RPR_ACTIVO_FILTRO ON ALP_RECETA_PRODUCCION(RPR_ACTIVO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_RECETA_DETALLE
-- Descripción: Detalle de materiales en la receta
-- Especifica materiales, cantidades y mermas
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_RECETA_DETALLE (
    RDT_RECETA_DETALLE       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RPR_RECETA_PRODUCCION    NUMBER NOT NULL,
    MAT_MATERIAL             NUMBER NOT NULL,
    RDT_CANTIDAD             NUMBER(12,2) NOT NULL,
    UNI_UNIDAD_MEDIDA        NUMBER NOT NULL,
    RDT_MERMA_PORCENTAJE     NUMBER(5,2) DEFAULT 0,
    
    CONSTRAINT FK_RDT_RECETA FOREIGN KEY (RPR_RECETA_PRODUCCION) 
        REFERENCES ALP_RECETA_PRODUCCION(RPR_RECETA_PRODUCCION),
    CONSTRAINT FK_RDT_MATERIAL FOREIGN KEY (MAT_MATERIAL) 
        REFERENCES ALP_MATERIAL(MAT_MATERIAL),
    CONSTRAINT FK_RDT_UNIDAD FOREIGN KEY (UNI_UNIDAD_MEDIDA) 
        REFERENCES ALP_UNIDAD_MEDIDA(UNI_UNIDAD_MEDIDA),
    CONSTRAINT CHK_RDT_CANTIDAD CHECK (RDT_CANTIDAD > 0),
    CONSTRAINT CHK_RDT_MERMA CHECK (RDT_MERMA_PORCENTAJE >= 0 AND RDT_MERMA_PORCENTAJE <= 100)
);

COMMENT ON TABLE ALP_RECETA_DETALLE IS 'Materiales y cantidades por receta (BOM detalle)';
COMMENT ON COLUMN ALP_RECETA_DETALLE.RDT_MERMA_PORCENTAJE IS 'Porcentaje de desperdicio esperado';

CREATE INDEX IDX_RDT_RECETA ON ALP_RECETA_DETALLE(RPR_RECETA_PRODUCCION);
CREATE INDEX IDX_RDT_MATERIAL ON ALP_RECETA_DETALLE(MAT_MATERIAL);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_RECETA_PROCESO
-- Descripción: Procesos necesarios en la receta
-- Define el flujo de trabajo (routing)
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_RECETA_PROCESO (
    RPC_RECETA_PROCESO       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RPR_RECETA_PRODUCCION    NUMBER NOT NULL,
    PCO_PROCESO              NUMBER NOT NULL,
    RPC_ORDEN                NUMBER NOT NULL,
    RPC_TIEMPO_ESTIMADO_MIN  NUMBER(10,2),
    
    CONSTRAINT FK_RPC_RECETA FOREIGN KEY (RPR_RECETA_PRODUCCION) 
        REFERENCES ALP_RECETA_PRODUCCION(RPR_RECETA_PRODUCCION),
    CONSTRAINT FK_RPC_PROCESO FOREIGN KEY (PCO_PROCESO) 
        REFERENCES ALP_PROCESO(PCO_PROCESO),
    CONSTRAINT UNQ_RPC_RECETA_ORDEN UNIQUE (RPR_RECETA_PRODUCCION, RPC_ORDEN),
    CONSTRAINT CHK_RPC_ORDEN CHECK (RPC_ORDEN > 0),
    CONSTRAINT CHK_RPC_TIEMPO CHECK (RPC_TIEMPO_ESTIMADO_MIN IS NULL OR RPC_TIEMPO_ESTIMADO_MIN > 0)
);

COMMENT ON TABLE ALP_RECETA_PROCESO IS 'Secuencia de procesos en receta (routing)';

CREATE INDEX IDX_RPC_RECETA ON ALP_RECETA_PROCESO(RPR_RECETA_PRODUCCION);
CREATE INDEX IDX_RPC_PROCESO ON ALP_RECETA_PROCESO(PCO_PROCESO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_ORDEN_PRODUCCION
-- Descripción: Órdenes de producción
-- Autorización para fabricar productos
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_ORDEN_PRODUCCION (
    ORP_ORDEN_PRODUCCION     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRO_PRODUCTO             NUMBER NOT NULL,
    RPR_RECETA_PRODUCCION    NUMBER NOT NULL,
    ORP_NUMERO               VARCHAR2(50) NOT NULL UNIQUE,
    ORP_CANTIDAD             NUMBER(12,2) NOT NULL,
    ORP_FECHA_INICIO         DATE,
    ORP_FECHA_FIN_ESTIMADA   DATE,
    ORP_ESTADO               VARCHAR2(20) DEFAULT 'BORRADOR' NOT NULL,
    
    CONSTRAINT FK_ORP_PRODUCTO FOREIGN KEY (PRO_PRODUCTO) 
        REFERENCES ALP_PRODUCTO(PRO_PRODUCTO),
    CONSTRAINT FK_ORP_RECETA FOREIGN KEY (RPR_RECETA_PRODUCCION) 
        REFERENCES ALP_RECETA_PRODUCCION(RPR_RECETA_PRODUCCION),
    CONSTRAINT CHK_ORP_CANTIDAD CHECK (ORP_CANTIDAD > 0),
    CONSTRAINT CHK_ORP_ESTADO CHECK (ORP_ESTADO IN ('BORRADOR', 'PROGRAMADA', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA')),
    CONSTRAINT CHK_ORP_FECHAS CHECK (ORP_FECHA_FIN_ESTIMADA IS NULL OR ORP_FECHA_FIN_ESTIMADA >= ORP_FECHA_INICIO)
);

COMMENT ON TABLE ALP_ORDEN_PRODUCCION IS 'Órdenes de fabricación';

CREATE INDEX IDX_ORP_PRODUCTO ON ALP_ORDEN_PRODUCCION(PRO_PRODUCTO);
CREATE INDEX IDX_ORP_ESTADO ON ALP_ORDEN_PRODUCCION(ORP_ESTADO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_ORDEN_PRODUCCION_DETALLE
-- Descripción: Detalle de procesos por orden de producción
-- Tracking de cada proceso
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_ORDEN_PRODUCCION_DETALLE (
    OPD_ORDEN_PRODUCCION_DETALLE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORP_ORDEN_PRODUCCION     NUMBER NOT NULL,
    PCO_PROCESO              NUMBER NOT NULL,
    OPD_ESTADO               VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    OPD_FECHA_INICIO         TIMESTAMP,
    OPD_FECHA_FIN            TIMESTAMP,
    
    CONSTRAINT FK_OPD_ORDEN FOREIGN KEY (ORP_ORDEN_PRODUCCION) 
        REFERENCES ALP_ORDEN_PRODUCCION(ORP_ORDEN_PRODUCCION),
    CONSTRAINT FK_OPD_PROCESO FOREIGN KEY (PCO_PROCESO) 
        REFERENCES ALP_PROCESO(PCO_PROCESO),
    CONSTRAINT CHK_OPD_ESTADO CHECK (OPD_ESTADO IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'PAUSADO', 'CANCELADO')),
    CONSTRAINT CHK_OPD_FECHAS CHECK (OPD_FECHA_FIN IS NULL OR OPD_FECHA_FIN >= OPD_FECHA_INICIO)
);

COMMENT ON TABLE ALP_ORDEN_PRODUCCION_DETALLE IS 'Tracking de procesos por orden';

CREATE INDEX IDX_OPD_ORDEN ON ALP_ORDEN_PRODUCCION_DETALLE(ORP_ORDEN_PRODUCCION);
CREATE INDEX IDX_OPD_PROCESO ON ALP_ORDEN_PRODUCCION_DETALLE(PCO_PROCESO);
CREATE INDEX IDX_OPD_ESTADO ON ALP_ORDEN_PRODUCCION_DETALLE(OPD_ESTADO);

-- ----------------------------------------------------------------------------
-- Tabla: PRD_ASIGNACION_PROCESO
-- Descripción: Asignación de empleados a procesos
-- Tracking de quién hace qué
-- ----------------------------------------------------------------------------
CREATE TABLE PRD_ASIGNACION_PROCESO (
    ASP_ASIGNACION_PROCESO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPD_ORDEN_PRODUCCION_DETALLE NUMBER NOT NULL,
    EMP_EMPLEADO             NUMBER NOT NULL,
    ASP_FECHA_ASIGNACION     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ASP_FECHA_FINALIZACION   TIMESTAMP,
    
    CONSTRAINT FK_ASP_ORDEN_DETALLE FOREIGN KEY (OPD_ORDEN_PRODUCCION_DETALLE) 
        REFERENCES ALP_ORDEN_PRODUCCION_DETALLE(OPD_ORDEN_PRODUCCION_DETALLE),
    CONSTRAINT FK_ASP_EMPLEADO FOREIGN KEY (EMP_EMPLEADO) 
        REFERENCES ALP_EMPLEADO(EMP_EMPLEADO)
);

COMMENT ON TABLE PRD_ASIGNACION_PROCESO IS 'Asignación de operarios a procesos';

CREATE INDEX IDX_ASP_DETALLE ON PRD_ASIGNACION_PROCESO(OPD_ORDEN_PRODUCCION_DETALLE);
CREATE INDEX IDX_ASP_EMPLEADO ON PRD_ASIGNACION_PROCESO(EMP_EMPLEADO);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_CONSUMO_MATERIAL
-- Descripción: Consumo real de materiales en producción
-- Vs. lo planificado en la receta
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_CONSUMO_MATERIAL (
    COM_CONSUMO_MATERIAL     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORP_ORDEN_PRODUCCION     NUMBER NOT NULL,
    MAT_MATERIAL             NUMBER NOT NULL,
    COM_CANTIDAD_CONSUMIDA   NUMBER(12,2) NOT NULL,
    COM_FECHA_CONSUMO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_COM_ORDEN FOREIGN KEY (ORP_ORDEN_PRODUCCION) 
        REFERENCES ALP_ORDEN_PRODUCCION(ORP_ORDEN_PRODUCCION),
    CONSTRAINT FK_COM_MATERIAL FOREIGN KEY (MAT_MATERIAL) 
        REFERENCES ALP_MATERIAL(MAT_MATERIAL),
    CONSTRAINT CHK_COM_CANTIDAD CHECK (COM_CANTIDAD_CONSUMIDA > 0)
);

COMMENT ON TABLE ALP_CONSUMO_MATERIAL IS 'Consumo real de materiales (vs. planificado)';

CREATE INDEX IDX_COM_ORDEN ON ALP_CONSUMO_MATERIAL(ORP_ORDEN_PRODUCCION);
CREATE INDEX IDX_COM_MATERIAL ON ALP_CONSUMO_MATERIAL(MAT_MATERIAL);

-- ----------------------------------------------------------------------------
-- Tabla: ALP_COSTO_PRODUCCION
-- Descripción: Costos de producción por orden
-- Permite costeo real vs. estándar
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_COSTO_PRODUCCION (
    COP_COSTO_PRODUCCION     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORP_ORDEN_PRODUCCION     NUMBER NOT NULL,
    COP_COSTO_MATERIALES     NUMBER(12,2) DEFAULT 0,
    COP_COSTO_MANO_OBRA      NUMBER(12,2) DEFAULT 0,
    COP_COSTOS_INDIRECTOS    NUMBER(12,2) DEFAULT 0,
    COP_COSTO_TOTAL          NUMBER(12,2) NOT NULL,
    
    CONSTRAINT FK_COP_ORDEN FOREIGN KEY (ORP_ORDEN_PRODUCCION) 
        REFERENCES ALP_ORDEN_PRODUCCION(ORP_ORDEN_PRODUCCION),
    CONSTRAINT UNQ_COP_ORDEN UNIQUE (ORP_ORDEN_PRODUCCION),
    CONSTRAINT CHK_COP_TOTAL CHECK (COP_COSTO_TOTAL >= 0)
);

COMMENT ON TABLE ALP_COSTO_PRODUCCION IS 'Costeo de órdenes de producción';

-- ----------------------------------------------------------------------------
-- Tabla: ALP_CONTROL_CALIDAD
-- Descripción: Inspecciones de calidad
-- Aseguramiento de calidad en producción
-- ----------------------------------------------------------------------------
CREATE TABLE ALP_CONTROL_CALIDAD (
    CCL_CONTROL_CALIDAD      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORP_ORDEN_PRODUCCION     NUMBER NOT NULL,
    EMP_EMPLEADO             NUMBER NOT NULL,
    CCL_RESULTADO            VARCHAR2(20) NOT NULL,
    CCL_OBSERVACIONES        CLOB,
    CCL_FECHA_INSPECCION     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_CCL_ORDEN FOREIGN KEY (ORP_ORDEN_PRODUCCION) 
        REFERENCES ALP_ORDEN_PRODUCCION(ORP_ORDEN_PRODUCCION),
    CONSTRAINT FK_CCL_EMPLEADO FOREIGN KEY (EMP_EMPLEADO) 
        REFERENCES ALP_EMPLEADO(EMP_EMPLEADO),
    CONSTRAINT CHK_CCL_RESULTADO CHECK (CCL_RESULTADO IN ('APROBADO', 'RECHAZADO', 'RETRABAJO'))
);

COMMENT ON TABLE ALP_CONTROL_CALIDAD IS 'Inspecciones de calidad de producción';

CREATE INDEX IDX_CCL_ORDEN ON ALP_CONTROL_CALIDAD(ORP_ORDEN_PRODUCCION);
CREATE INDEX IDX_CCL_RESULTADO ON ALP_CONTROL_CALIDAD(CCL_RESULTADO);

-- ============================================================================
-- FIN BLOQUES 6 Y 7 - INVENTARIOS Y PRODUCCIÓN
-- ============================================================================

SELECT 'BLOQUES 6 y 7 COMPLETADOS - Inventarios y Producción' AS ESTADO FROM DUAL;
